input_video: "data/input.mp4"
output_dir: "outputs"
output_video: "annotated.mp4"
preview:
  enabled: true
  scale: 0.5

# feature:
#   - regionpresence
#  - linecross

#lines:
#  - id: 1
#    bidirectional: true
#    orientation: horizontal
#    direction: downward
#    coords:
#      - x: 0.29375
#        y: 0.441667
#      - x: 0.75
#        y: 0.454167
# regions:
#   - id: 1
#     name: "waiting_area"
#     coords:
#       - x: 0.0
#         y: 0.0
#       - x: 0.999
#         y: 0.0
#       - x: 0.999
#         y: 0.999
#       - x: 0.0
#         y: 0.999

model:
  weights: "models/best.pt"
  device: "cpu"
  conf: 0.25
  iou: 0.45
  classes: [0]
  tracker: "bytetrack.yaml"

