input_video: data/input.mp4
output_dir: outputs
output_video: annotated.mp4

model:
  weights: models/best.pt
  device: cpu
  conf: 0.25
  iou: 0.45
  classes:
  - 0
  tracker: bytetrack.yaml

preview:
  enabled: true
  scale: 0.5

roi:
  setup_on_start: true

feature:
- linecross
- regionpresence

lines:
- id: 1
  bidirectional: true
  orientation: horizontal
  direction: downward
  coords:
  - x: 0.25078125
    y: 0.3902777777777778
  - x: 0.7859375
    y: 0.45

regions:
- id: 1
  name: region_1
  dwell_threshold_sec: 5
  coords:
  - x: 0.1
    y: 0.1
  - x: 0.5
    y: 0.1
  - x: 0.5
    y: 0.5
  - x: 0.1
    y: 0.5
